### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by nitanmarcel** [matrix-org/mjolnir#105]
**Describe the bug**

**To Reproduce**
After editing the config file just run the docker image with `docker run --rm -it -v /etc/mjolnir:/data matrixdotorg/mjolnir:latest`

**Expected behavior**
Should not fail (duh)

**Additional context**
Running on a debian vps. `matrix-synapse==1.36.0`

~~~
/mjolnir/index.js:93
            if (!joinedRooms.includes(roomId)) {
                             ^

TypeError: Cannot read property 'includes' of undefined
    at /mjolnir/index.js:93:30
    at Generator.next (<anonymous>)
    at fulfilled (/mjolnir/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
~~~

**Comment by turt2live** [comment]
This looks like something went wrong prior to the error. If this happens again, I'd recommend visiting the support room on Matrix rather than opening an issue.

**Comment by nitanmarcel** [comment]
> This looks like something went wrong prior to the error. If this happens again, I'd recommend visiting the support room on Matrix rather than opening an issue.

xD it has been 4 years since the issue
