### ISSUE TITLE
Migrate antispam module to Synapse's new modules system

### ISSUE THREAD

**Issue by babolivier** [matrix-org/mjolnir#112]
See https://matrix-org.github.io/synapse/develop/modules.html#porting-an-existing-module-that-uses-the-old-interface

The legacy interface will be removed from Synapse in August 2021.

**Comment by richvdh** [comment]
For my own reference: the updated spam_checker interface was added in [Synapse 1.37](https://github.com/matrix-org/synapse/blob/develop/CHANGES.md#synapse-1370-2021-06-29).

Deprecation notice at https://matrix-org.github.io/synapse/develop/upgrade#deprecation-of-the-current-spam-checker-interface.

In practice I think we might delay this: see https://github.com/matrix-org/synapse/issues/10469.
