### ISSUE TITLE
Update for new official event types

### ISSUE THREAD

**Issue by turt2live** [matrix-org/mjolnir#12]
https://github.com/matrix-org/matrix-doc/pull/2313

**Comment by Gnuxie** [comment]
Ok so it turns out that the spec says the type is `m.policy.rule.x` but for some reason all of mjolnir is written as `m.room.rule.x`...

https://github.com/matrix-org/mjolnir/blob/main/src/models/BanList.ts#L20-22

**Comment by turt2live** [comment]
the event types changed at the last minute :( 

mjolnir should interpret `m.room.rule` but it should stop publishing that.

**Comment by turt2live** [comment]
I think we did this? If not, a new issue would be good.
