### ISSUE TITLE
Accept invites based on space membership

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/mjolnir#125]
Now that spaces are about to come out of beta, we should add the option for Mjolnir to accept room invitations based on if the inviter is in a certain space. Similar to how `acceptInvitesFromGroup` works today.

Possibly also deprecate the `acceptInvitesFromGroup` option at the same time?

**Comment by Yoric** [comment]
So, a pref that tells a Mjolnir deployment to accept all invites from inviters who belong to a given space?
Is there an API to determine that a user belongs to a space?

**Comment by turt2live** [comment]
The same APIs that tell you if a user is a member of a room: Spaces are Rooms.

**Comment by Gnuxie** [comment]
https://github.com/matrix-org/mjolnir/pull/338
