### ISSUE TITLE
fallback text/rendering for Riot 

### ISSUE THREAD

**Issue by f0x52** [matrix-org/mjolnir#15]
It would be nice if Riot can render the rule events, so I can join someone else's banlist room, and keep track manually, without giving their banlist full control over my room

**Comment by turt2live** [comment]
another theory is that Mjolnir could support a double-confirmation system where it requires 2+ rules for the same entity to be in effect before it applies it.

**Comment by turt2live** [comment]
I've separated the multiple confirmation part to https://github.com/matrix-org/mjolnir/issues/18 - I'll spin out a riot-web PR for rendering the events.
