### ISSUE TITLE
Abuse report buttons do not work (in an encrypted moderation room?)

### ISSUE THREAD

**Issue by heftig** [matrix-org/mjolnir#153]
**Describe the bug**
The buttons on the abuse reports do nothing.

**To Reproduce**
1. Report an event.
2. Click on any of the report's buttons in the management room.

**Expected behavior**
Mjolnir reacts to the click.

**Additional context**
- Mjolnir is set up through Pantalaimon and the management room is encrypted.
- I've tried the buttons using Element Web and Element Android.
- Element Android tells me Mjolnir's reaction events are encrypted, while my own (from both Web and Android) are unencrypted.

**Comment by cremesk** [comment]
maybe this is related to the encrypted managment room.

here it works fine. the different is my management room is unencrypted.

![screenshot](https://matrix.envs.net/_matrix/media/r0/download/envs.net/9e2631cca00875d2050f7658c384d13597e65c7d)

(i use also mjolnir via pantalaimon)

OS: Debian 11
nodejs v: 14.18.1
yarn v: 1.22.15

**Comment by Yoric** [comment]
@heftig Can you confirm that you're using Mjölnir 1.2.1? There was a snafu this week and I initially tagged/released an image that didn't contain all the patches.

**Comment by heftig** [comment]
Yes, sorry. Mjolnir 1.2.1, installed via git.

**Comment by Yoric** [comment]
One thing that is going to make testing/fixing this complicated is that the test suite doesn't support pantalaimon yet. I'll check how hard it would be to add support.

**Comment by Yoric** [comment]
In the meantime, @heftig, do you see any errors show up in the logs?

**Comment by heftig** [comment]
No, I already looked. There's no reaction from Mjolnir, not even logs.

**Comment by TildeSlashC0re** [comment]
> No, I already looked. There's no reaction from Mjolnir, not even logs.

well it DOES receive the `m.reaction` event but it seems to be ignored when coming from an encrypted management room.

similar setup on my end, except for a docker build via the currently supplied dockerfile in the main-branch.
can confirm this behavior as described.

**Comment by heftig** [comment]
I tried a report-to-moderators via msc3215, which was delivered successfully, but the bot still does not react to using any of the reactions on the report message.

**Comment by turt2live** [comment]
I am presuming this is fixed because it doesn't make sense to be broken. If this is still happening, please open a new issue with fresh details/logs.

**Comment by Gnuxie** [comment]
It's not fixed, reactions don't work with Pantalaimon for some reason and we don't know why.

**Comment by turt2live** [comment]
We're deprecating Pantalaimon with https://github.com/matrix-org/mjolnir/releases/tag/v1.8.0, so quickly becomes a non-issue.
