### ISSUE TITLE
Abuse report UX: buttons unreadable in dark mode on android element

### ISSUE THREAD

**Issue by sealne** [matrix-org/mjolnir#154]
**Describe the bug**
The buttons below a report in the moderation room when viewed from Element Android in dark mode are almost unreadable
![Screenshot_20211119-094051_Element-crop](https://user-images.githubusercontent.com/4383078/142602348-b93cd0e2-4774-4dbf-ae6e-61ea411d23fe.png)

**To Reproduce**
1. View moderation room in android with dark mode on and an abuse report visible
2.  See error

**Expected behavior**
Should use white text and dark mode icons as it does in web element
![Screenshot_20211119_095231](https://user-images.githubusercontent.com/4383078/142602839-597573a5-4969-4945-a38d-44a07b174867.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Xiaomi Mi5sp
 - OS: [e.g. iOS8.1] Android 9 (linage os)
 - Version [e.g. 22] 1.33 (fdroid)

**Comment by sealne** [comment]
on my phone it was even less readable than it looks here from this screenshot viewed on my laptop

**Comment by Yoric** [comment]
It does look hard to read but I don't think that a bot has any control on how buttons are displayed.

Feels like an issue that should be filed on Element Android.

**Comment by turt2live** [comment]
This looks like a client issue.
