### ISSUE TITLE
Feature Request: Enable/Disable Protections on a individual rooms instead of all or none

### ISSUE THREAD

**Issue by AnonyPla** [matrix-org/mjolnir#157]
**Is your feature request related to a problem? Please describe.**
It would be interesting to have a way to enable/disable protections on a per room basis and not either on all or no rooms.

**Describe the solution you'd like**
Enable/Disable protections individually on each protected room

**Describe alternatives you've considered**
None found really

**Additional context**
No additional context

**Comment by turt2live** [comment]
This goes somewhat against the idea of Mjolnir, which is a full community protection bot.
