### ISSUE TITLE
Egress throttled operation mode

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/mjolnir#165]
**Is your feature request related to a problem? Please describe.**
There are Matrix servers with rate limits we are not allowed to alter. Currently, Mjolnir fails to work when used at such servers.

**Describe the solution you'd like**
The bot should queue the actions into a FIFO, and perform those actions one by one while throttling itself back to single-user level of rate limits.

**Additional context**
Commercial Matrix servers with third party communities are an example of this.

**Comment by turt2live** [comment]
A queue would delay response to an incident. It is highly undesirable to let Mjolnir work in an environment where support requests end up becoming "it's slow", thus it cannot be rate limited.

Future moderation tooling in Matrix will tackle Mjolnir's functionality without being subject to such extreme conditions.

Closing as wont fix.
