### ISSUE TITLE
Automatic ban from a protection has over-eager redactions

### ISSUE THREAD

**Issue by grahamc** [matrix-org/mjolnir#180]
**Describe the bug**

Redactions of banned users take place even after the user is unbanned.

**To Reproduce**
1. Use the FirstMessageIsImageProtection protection.
1. A well known user joins a room for the first time.
2. They post an image as their first message.
3. They're banned.
4. Their post is redacted.
3. The user did not deserve the ban, so they're unbanned.
4. They join the room again.
5. They post a message.
6. Mjolnir redacts their messages.

**Expected behavior**
I expect Mjolnir to stop redacting a user's messages after they're unbanned.

**Screenshots**

The "L" and "P" messages deleted near the end are by Mjolnir, after I unbanned both L and P users.

![image](https://user-images.githubusercontent.com/76716/149244837-cf35e52f-5834-4016-9744-a5effa8ebe06.png)

**Desktop (please complete the following information):**
I don't think this is related, but I'm on  NixOS 21.11 and:

Element version: 1.9.4
Olm version: 3.2.3

**Additional context**
Mjolnir 1.2.1

**Comment by Twi1ightSparkle** [comment]
Saw this yesterday with a customer Mjolnir. v1.3.1. Mjolnir stopped redacting the affected user after a restart. There are nothing in the logs when this happens. Message me for unredacted logs or access to the relevant moderation room.
<img width="1093" alt="Screen_Shot_2022-02-15_at_5_39_10_PM" src="https://user-images.githubusercontent.com/19155609/154118317-e6ce442a-7636-47e3-bcb7-c4913321cd91.png">

The user was still being redacted 30 minutes after the "is no longer considered suspect" log entry.

Manually unbannign the user doesn't work as it's not on a ban list.

![Screen_Shot_2022-02-15_at_5_43_53_PM](https://user-images.githubusercontent.com/19155609/154118885-a9e1183c-b757-4430-a3b3-1f1a758e49ef.png)

**Comment by turt2live** [comment]
This is somewhat deliberate, but there's things we can do to make it easier to unban someone. Closing in favour of https://github.com/matrix-org/mjolnir/issues/530
