### ISSUE TITLE
Powerlevel allows illegal characters in the user identifier

### ISSUE THREAD

**Issue by MichaelSasser** [matrix-org/mjolnir#201]
**Describe the bug**
`!mjolnir powerlevel` does not check for illegal characters in the user identifier. If I remember that correctly, only lowercase letters, numbers, underscores, and dashes are allowed.

**To Reproduce**
It is possible to set the powerlevel using a user identifier with illegal characters. (Tested with mjolnir v1.2.1)

1. `!mjolnir powerlevel @FooBarBaz:matrix.org 50` (Uppercase letters are not allowed, I haven't tested other characters)
2. See room roles & permissions

**Expected behavior**
The bot should throw an error.

**Comment by tulir** [comment]
Note that uppercase letters are allowed in [historical user IDs](https://spec.matrix.org/v1.1/appendices/#historical-user-ids) (meaning there are real users with uppercase user IDs), and arbitrary unicode is allowed in user IDs over federation (meaning a server admin could create user IDs with any unicode characters and other servers will accept them). See also: https://github.com/matrix-org/matrix-doc/pull/2828

**Comment by MichaelSasser** [comment]
Thanks for your detailed response. Since this is a feature, I close the issue.
