### ISSUE TITLE
Batch ACL updates

### ISSUE THREAD

**Issue by babolivier** [matrix-org/mjolnir#203]
Mjolnir doesn't batch ACL updates, which means that it sends each new rule as a separate event. This is quite inconvenient when there are many updates to send at once (more than 70 today) and some of the rooms are high SNR ones (such as the Synapse announcements room) where it wouldn't be unrealistic to expect most members to have notifications set to "All messages" (since ACL changes generate notifications, see https://github.com/vector-im/element-web/issues/20788).

**Comment by Yoric** [comment]
Doesn't seem *too* difficult to implement. I think Mjölnir is due some maintenance on ACLs anyway, so we could introduce an ACL batch event.
