### ISSUE TITLE
Mitigate spammers using mass mentions 

### ISSUE THREAD

**Issue by Caspy7** [matrix-org/mjolnir#211]
**Is your feature request related to a problem? Please describe.**
A spammer came into a room I manage and sent several messages. Each one started with a URL then the rest was just mentions of everyone in the channel. I don't know if they managed to ping the whole room before I was able to ban them, but there were hundreds.

**Describe the solution you'd like**
Detect the number of user mentions in a message and act on that to prevent abuse from spammers.
I don't know the best solution which is why I'm not being explicitly prescriptive. I know we want users to be able to use a "normal" amount of mentions. 
Perhaps when X number of mentions are detected we prevent the message from posting and inform the user of the limitation. And if they exceed a certain number of mentions in a short period of time we mute them and notify admins/mods.

**Additional context**
I presume the @room function is blocked for most users by default. This prevents casual users from abusing that notification, but if a spammer can automate the process described above they can achieve the same ends.

**Comment by TheTimeWalker** [comment]
You're 36 minutes too late :)
https://github.com/matrix-org/mjolnir/pull/210
