### ISSUE TITLE
unbans are not applied

### ISSUE THREAD

**Issue by Cadair** [matrix-org/mjolnir#22]
Either I am misunderstanding something or it's broken, I have banned someone:

```
!mjolnir ban sunpy user @Nabobalis:matrix.org Test ban
```
the state event get's put in the ban list, and the bans are issued over all the rooms as expected.

running
```
!mjolnir unban sunpy user @Nabobalis:matrix.org true
```
removes the ban from the ban list but doesn't actually reverse the ban in any of the rooms. (This was the only ban in the ban list, so nothing else should be getting in the way).

**Comment by turt2live** [comment]
confirmed indeed. Probably happened when the ban command got "smarter". For now it's best to reverse the ban manually (and usually the social pressure for such a thing isn't as important).
