### ISSUE TITLE
Make banlist collaboration easier by offering to preview effects before subscribing

### ISSUE THREAD

**Issue by bkil** [matrix-org/mjolnir#228]
* We already protect dozens of rooms based on an existing ban list.
* We would like to subscribe to a new ban list from another trustworthy operator.
* Before we subscribe, we would like to make sure that the new ban list will not have any adverse effect in our protected rooms.
* mjolnir should ask for a confirmation upon subscription if any existing users would be affected by new Server ACL or ban rules.

**Comment by bkil** [comment]
The same kind of confirmation or preview function should be provided in any other case when mjolnir starts moderating.

For example, when you protect a new room or after the permission level of the bot is promoted within a given room that allows it to complete a new type of action (i.e. banning or server ACL).

**Comment by bkil** [comment]
#240 is also related in that newly introduced ban rules could be tested against or grouped by the seniority of the affected user.

I.e., it might be less dangerous if a new ban rule only applied to users who joined recently or who have never spoken in the past, because those may very well be puppets themselves.

**Comment by turt2live** [comment]
I think this is effectively https://github.com/matrix-org/mjolnir/issues/18

**Comment by bkil** [comment]
No, it is not.
