### ISSUE TITLE
ability to compare the hash of a picture with a list

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/mjolnir#229]
**Is your feature request related to a problem? Please describe.**
At the moment in several german rooms there is a person (probably from japan) who uses several matrix homeservers for creating a account, disguised as another user, and post offensive pictures.

**Describe the solution you'd like**
mjolnir should be able to look up the hash value of a picture and if the hash is on the list, he should be able do delete the picture (and ban the user)

**Describe alternatives you've considered**
Writing a Bot for this...

**Comment by bkil** [comment]
This might fend off a few unsophisticated script kiddies, but it could be worked around easily in an automated fashion just by resaving the jpeg (at another quality level or after adding any amount of fractional blurring, sharpening, color enhancement, etc).

I think proper solutions are too expensive to implement within the scope of a project that struggles to finish even the basics:

- https://en.wikipedia.org/wiki/Perceptual_hash
- https://en.wikipedia.org/wiki/Digital_video_fingerprinting
- https://en.wikipedia.org/wiki/Reverse_image_search#Algorithms
- https://en.wikipedia.org/wiki/List_of_CBIR_engines#CBIR_research_projects/demos/open_source_projects
- https://en.wikipedia.org/wiki/Content-based_image_retrieval#Techniques
- https://en.wikipedia.org/wiki/Automatic_image_annotation

Related: #181  #148

**Comment by Yoric** [comment]
> I think proper solutions are too expensive to implement within the scope of a project that struggles to finish even the basics:

Harsh but not entirely false.

It's a good idea but I don't think we'll have time to work on it in the near future. Patches welcome, though!

**Comment by JokerGermany** [comment]
There is someone who is writing a bot for this issue at the moment.
He says it's "chaos code" at the moment^^
https://github.com/Unkn0wnCat/matrix-veles

**Comment by turt2live** [comment]
Hash matching of any variety is best done at the server level rather than room level. Mjolnir has NSFW protections these days which does something similar, but the idea of hash matching is best done external to the bot.
