### ISSUE TITLE
Option to prefix ban reason with ban list name, ban entry time and local ban density

### ISSUE THREAD

**Issue by bkil** [matrix-org/mjolnir#231]
- Assume that you are watching multiple foreign ban lists.
- You are seeing someone being banned from your room.
- You may want to better understand why they got banned.
  - Not all moderators provide detailed reasoning to their ban rules.

Hence it would be helpful when Mjolnir bans someone from a room based on a rule, it should include as much metadata in the ban reason as possible. This includes:

- The original reason string (if it was provided)
- The ban list and/or the short code
- The time of the ban list entry
- Optionally the ban entry density in the ban list at the point of time the rule was created (i.e., how many bans were added within 1 hour and 1 day radius) This could prove to be valuable information for debugging and "forgiveness", because in case of spam waves, certain moderators are trigger happy to ban anyone entering a room.

It would be also helpful to know the original room (possibly with a link to an unredacted message just before that) where abusive behavior was practiced that led to a ban, but I understand that this information is not available in the current workflow and architecture.

**Comment by bkil** [comment]
Somewhat related: #228

**Comment by turt2live** [comment]
These sound like things which would be best attached as threads to the ban command being issued, for internal tracking. Mjolnir doesn't really have a database it can use to store this, and not all this information should be public by default. 

We'd likely accept PRs which add notes functionality, but are unlikely to consider it an in-scope feature for Mjolnir at this time.
