### ISSUE TITLE
Precondition protections based on seniority

### ISSUE THREAD

**Issue by bkil** [matrix-org/mjolnir#240]
We would like it if certain protections (prohibition of images, certain words, external links, rate limits) would only apply to new members who we have not talked to before.

One can keep track of seniority within a room by increasing the power level of members over time.
It would be useful if a given protection could be set to only apply to users below a certain power level.

**Comment by turt2live** [comment]
Protections are meant to apply to all users, deliberately. Adding too many heuristics opens the room up to abuse (user creates account, idles for 2 days, floods).

We can however make it easier to recover from an automated action: https://github.com/matrix-org/mjolnir/issues/530

**Comment by bkil** [comment]
I don't see that issue relevant here. Time was never mentioned here, neither was banning, nor unintended actions. Let me simplify this issue for you:

* we want to use 4 power levels in the room: default (0), member (10), mod (50), admin (100)
* PL below 10 could be prohibited from setting an avatar or display name, attaching files, typing certain words, adding external links and be subject to comment rate limits
* PL at or above 10 could do whatever they want
* the mods and admins can elevate trustworthy people based on reputation from 0 to 10 manually

**Comment by turt2live** [comment]
thanks for the clarification! This sounds like something that would be best handled at the spec level rather than within Mjolnir. Other forks of Mjolnir may be more able to take on the work while the spec options are explored, however.
