### ISSUE TITLE
Option "BasicFloodingProtection" bans people for redacting messages

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/mjolnir#252]
**Describe the bug**
When you have 
> 🟢 (enabled) BasicFloodingProtection - If a user posts more than 10 messages in 60s they'll be banned for spam. This does not publish the ban to any of your ban lists.

enabled, mjolnir is Admin and a Mod redacts (spam) messages, the Mod will be kicked.

**To Reproduce**
1. Invite mjolnir in a room, make the bot admin. 
2. activate BasicFloodingProtection
3. Make 10 messages with a user.
4. Let a Mod Delete the 10 messages of the user

**Expected behavior**
1. Mjolnir shouldn't ban for redacting
2. Mjolnir shouldn't ban Mods and not try to ban admins ;)

**Additional context**
As a Workarround:
Insert in the description of BasicFloodingProtection, that Mjolnir should only be Mod and NOT Admin, when this option is used.

**Comment by turt2live** [comment]
This is expected behaviour. Flooding is flooding when the protection is enabled.
