### ISSUE TITLE
Setup and documentation improvements

### ISSUE THREAD

**Issue by Andre2344** [matrix-org/mjolnir#26]
Hi,

thank you for your great job and this cool software!
I just want to leave some suggestions for improvements and say where the setup needs some explanation:

* Explain where to get access token. When logging in to riot, copy the access key and log out, the access key is outdated
* Docker container refused to start until i deleted /config/default.yaml even if production.yaml exists
* Docker container refused to start when not having set "protectedRooms" even if protectedAllJoinedRooms is set to true
* Explain how to kill container and/or to run in background when started like in your documentation
* Explain how to set up ACL and ban lists

**Comment by turt2live** [comment]
Some of this like killing the container, restarting, etc are more of a sysadmin problem than this project's concern. How you deploy this is ultimately your decision - the project just gives you a way to see what sorts of stuff it is expecting (ports, etc).

**Comment by zyphlar** [comment]
I know it should be obvious, but to new admins who don't necessarily know otherwise it's useful to just mention how to get access tokens since that's the first step https://webapps.stackexchange.com/a/138497
