### ISSUE TITLE
Abillity to control mjolnir like beeing in the room

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/mjolnir#261]
**Is your feature request related to a problem? Please describe.**
There should be a way of doing things "manual" in critical situations.
e.g. unbanning because mistakes can happen.

I made the issue #257 , but now i think i understand the concept behind mjolnir better and i would like to separate prevention and reaction.
Therefore i think #257 isn't the right way.

This problem happend with a bug in version 1.4.0:
A user was banned because of the basic flooding protection and even a restart couldn't unban the user....

**Describe the solution you'd like**
I would like a way to control the mjolnir in a way like i would as a normal user in that room.
command:
`!mjolnir control "<message>" <room>`
e.G.
`!mjolnir control "/unban @example:example.com" #example:example.com`
If no room is given you need to use the --force flag.

**Describe alternatives you've considered**
#257 which didn't fulfill everything which this solution can do.

**Comment by turt2live** [comment]
The core concern here is addressed by https://github.com/matrix-org/mjolnir/issues/530
