### ISSUE TITLE
Make it easier to get a list of banned users/servers/rooms 

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/mjolnir#263]
**Is your feature request related to a problem? Please describe.**
I wanted to look which server are banned on which list.
It looks really hard to find such infos.

**Describe the solution you'd like**
I would like two ways to reach this.
1.
- Add the banned users to the banned list of the room of the list
- Add the banned servers as acl to the room of the list

e.G.
When matrix.org is banning a user, the user should be banned in [#matrix-org-coc-bl:matrix.org](https://matrix.to/#/#matrix-org-coc-bl:matrix.org), too.
When matrix.org is banning a server, the server should be added to the acl of [#matrix-org-coc-bl:matrix.org](https://matrix.to/#/#matrix-org-coc-bl:matrix.org)

2.
`!mjolnir export <users>/<servers>/<rooms> <list>`

`!mjolnir export users <list>` should output all banned users of a list 
`!mjolnir export servers <list>` - should should output all banned servers of a list
`!mjolnir export rooms <list>` - should output all rooms, with are shutdowned
(preferable as downloadable *.txt file)

**Comment by turt2live** [comment]
I'm considering this fixed by https://github.com/matrix-org/mjolnir/pull/307 - exporting doesn't really feel like something Mjolnir should have at the moment.
