### ISSUE TITLE
M_LIMIT_EXCEEDED errors

### ISSUE THREAD

**Issue by Andre2344** [matrix-org/mjolnir#27]
And i get many of these errors:
```
  errcode: 'M_LIMIT_EXCEEDED',
  error: 'Too Many Requests',
```
This could be because of ratelimiting in synapse. Maybe a proper rc_admin_redaction value could solve the problem?

**Comment by turt2live** [comment]
https://github.com/matrix-org/mjolnir/issues/23

**Comment by Loader009** [comment]
This is the "fix"?
You basically tell us, to not use Mjolnir on servers of which you don't have control of.
