### ISSUE TITLE
Refactoring application of bans and ACL

### ISSUE THREAD

**Issue by Gnuxie** [matrix-org/mjolnir#273]
https://github.com/matrix-org/mjolnir/pull/164

Application of bans and ACL is extremely slow with a large number of moderately sized rooms (50+ with a few 20k~ user rooms) 

- [x] We should apply bans and server ACL concurrently to the most recently active rooms first.
      This means rooms where incidents have are taking place get seen to first.
- [ ] [Kick](https://github.com/matrix-org/mjolnir/issues/161) users from servers who have been ACL'd because of the unreliability of server ACL. appservice irc already does this so you should be able to copy [their](https://github.com/matrix-org/matrix-appservice-irc/pull/1532) [approach](https://github.com/matrix-org/matrix-appservice-irc/pull/1551)
- [ ] Revisit the redaction queue and when redaction happens, it is known to be unreliable. Start by cutting out the hack for initial sync and [removing](https://spec.matrix.org/unstable/client-server-api/#get_matrixclientv3roomsroomidmessages) `from` from [here](https://github.com/matrix-org/mjolnir/blob/main/src/utils.ts#L107). 
- [ ] Keep a rolling cache of room state (members, acl) for each protected room that is updated along side the client sync (similar to banlists). This means we can eliminate client api calls to `/joined_members` and `m.room.server_acl` in larger rooms, which can save minutes of time for large rooms. We'll want to be smart about members because with a few large rooms this cache can become too big. Lazy members might be worth a look, this isn't an easy problem

**Comment by turt2live** [comment]
I think the remainder of this is largely https://github.com/matrix-org/mjolnir/issues/161
