### ISSUE TITLE
Provide a docker container with pantalaimon

### ISSUE THREAD

**Issue by Cadair** [matrix-org/mjolnir#28]
It would be nice to have a docker container preconfigured with pan installed, so that it can be easily activated in some manner. Either in the main container or a separate tag.

**Comment by turt2live** [comment]
People in the docker community might have our heads for supplying two apps in one container. We might want to consider a docker-compose file that Just Works™ instead?

**Comment by Cadair** [comment]
I have weird deployment things where I really want it in one container, but either works.

**Comment by turt2live** [comment]
we're deprecating pantalaimon support in favour of native encryption via rust-sdk
