### ISSUE TITLE
Splitting of management room and logs

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/mjolnir#287]
#### Is your feature request related to a problem? Please describe.
Currently, the management room of mjolnir will be busy with moderators putting in commands, and mjolnir outputting results, often both at the same time.

However, its difficult to go through this if a moderator starts inputting a lot of commands, or the bot is spewing a lot of decisions.

#### Describe the solution you'd like.
Have some way to "split" the stream of information, either have the audit log be sequestered in a long-running thread, or in a different room entirely.

Note: A consequence of this would be that command actions are hard to immediately "eye", as the bot will output it in another room, while currently most clients (other than hydrogen) only allow viewing a single chat at a time.

**Comment by turt2live** [comment]
It's a feature to have both of these functions in the same room.
