### ISSUE TITLE
Feature request: Make the name Mjolnir responds to configurable.

### ISSUE THREAD

**Issue by virtadpt** [matrix-org/mjolnir#29]
How tricky would it be to make the name the Mjolnir bot responds to configurable?  Calling it with !mjolnir works, to be fair, but when the account's not named mjolnir:matrix.example.com it can be a bit confusing, especially when the banhammer must be swung in broad arcs, if you catch my drift.

Being able to set an arbitrary name in the config file (like !anton or !nuke) but defaulting to !mjolnir would be really handy.

**Comment by Randshot** [comment]
@virtadpt From what I can see, it should be as simple as making `COMMAND_PREFIX` modifiable via the config file, and optionally also use the given prefix in the help/status messages, instead of hard-coding the prefix into the message.

**Comment by turt2live** [comment]
What's wrong with just using the bot's display name? You can already tab complete and ping the bot instead of using `!mjolnir`.
