### ISSUE TITLE
Lots of duplicates in moderation room messages

### ISSUE THREAD

**Issue by f0x52** [matrix-org/mjolnir#3]
After giving the error message about missing PL in certain rooms, the bot will start spamming the moderator room with messages, presumably because it's still trying to update there but failing
![afbeelding](https://user-images.githubusercontent.com/23422690/66384002-3beda980-e9be-11e9-8539-44a06d919192.png)

**Comment by f0x52** [comment]
Even with the correct PL this happens, tons of duplicate "updating member bans" messages

**Comment by turt2live** [comment]
This can be one of about 4 things:
1. The room is listed multiple times.
2. When the bot was started for the first time, the sync had a bunch of member events in it.
3. Your room has a lot of membership changes.
4. The bot banned a bunch of people and was working around possible state resets by re-validating the membership in the room.

**Comment by f0x52** [comment]
I think 2 is the only plausible option here. OTOH, after updating this doesn't seem to happen anymore

**Comment by turt2live** [comment]
Going to consider that fixed for now. If it happens again, please open a new issue.
