### ISSUE TITLE
support ignoring invites silently for the synapse plugin

### ISSUE THREAD

**Issue by thestinger** [matrix-org/mjolnir#300]
Element implements ignoring invites by never handling them. This is useful because the people sending the invites don't know that the invite has been ignored. Mjolnir's synapse plugin always loudly rejects them which helps the people spamming by letting them know the invites weren't received, so they know they need to send new ones from new accounts not caught by the ban list, which could mean changing their username pattern or home server.

**Comment by H-Shay** [comment]
I think, looking at the code, that the rejection is actually handled in the synapse code - the mjolnir anti-spam module implements a `user_may_invite` function, but this function only returns a boolean to the synapse code that calls it. Thus I think that rejecting the invite silently would need to happen in synapse.

**Comment by H-Shay** [comment]
https://github.com/element-hq/synapse/issues/17492

**Comment by turt2live** [comment]
Closing in favour of upstream for now: https://github.com/element-hq/synapse/issues/17492
