### ISSUE TITLE
Flagging users

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/mjolnir#304]
#### Is your feature request related to a problem? Please describe.
Sometimes when I observe a different chat, I see a user which would likely join the mjolnir-moderated community, but hasn't yet. This user would then exhibit behaviours and vibes which aren't appropriate for the community.

#### Describe the solution you'd like
I'd like to be able to "tag" or "flag" this user, (privately with the bot, if possible), so that I am pinged when this user joins a protected room.

This flag would not be federated onto a policy list, and it's likely this would not become a policy, as not to have a user become "strongly prejudiced" to be banned or kicked, but to have admins be aware that a user they noticed in another room, has now joined their community.

**Comment by turt2live** [comment]
My understanding of our legal obligations for matrix.org make this a feature that's difficult and likely impossible to support. We cannot (and should not) be creating lists of users which are being monitored. 

Forks of Mjolnir may be interested/able to implement this feature, however.
