### ISSUE TITLE
[Feature] Specify a list of allowed or ignored username globs

### ISSUE THREAD

**Issue by 0xC0ncord** [matrix-org/mjolnir#321]
**Is your feature request related to a problem? Please describe.**
Currently I am using Mjolnir to protect a room that is also bridged to other platforms, namely Telegram. I am also using the `FirstMessageIsImageProtection` protection to combat spam. I rely on dedicated Telegram moderators to deal with spam in the corresponding Telegram group.

Unfortunately, if a user joins the Telegram group and posts an image as the first message, Mjolnir will ban the puppet user on Matrix.

**Describe the solution you'd like**
There should be a way to specify a list of "trusted" or otherwise ignored username globs such that Mjolnir will not monitor any of their messages or attempt to take action against them. This can also be used to make Mjolnir ignore server administrators, if desired. In the above case, the following would solve the problem:
```
ignored_users:
- '@admin:myserver.org'
- '@_telegram_*:myserver.org'
- '@_discord_*:myserver.org'
```

**Describe alternatives you've considered**
To work around the above problem case, an administrator or moderator would need to tell Mjolnir to unban the Telegram puppet user and Mjolnir will need to be restarted in order to stop deleting that user's messages. This is largely inconvenient.

It may be more desirable to configure ignored or trusted username globs on a per-protection basis rather than globally for all protections.

**Comment by turt2live** [comment]
We're unlikely to add an arbitrary list, but we can be better about how we handle it: https://github.com/matrix-org/mjolnir/issues/200
