### ISSUE TITLE
protectedRooms array in the configuration file doesn't work without either protectAllJoinedRooms set to true or adding the rooms to the account data via commands

### ISSUE THREAD

**Issue by thestinger** [matrix-org/mjolnir#330]
Setting `protectAllJoinedRooms: false` results in mjolnir not enforcing bans for rooms in `protectedRooms` until a state event triggers an update for a room. This means it won't ban users who are on a ban list and already in a protected room until a state event triggers it. If you add the rooms via the command in addition to having them in `protectedRooms` it also avoids the issue. That means the issue has something to do with the `protectedRooms` array only applying in some contexts but not others.

**Comment by turt2live** [comment]
I believe this has been fixed. If not, please open a new issue with fresh logs.
