### ISSUE TITLE
Add a way to shut down rooms without creating a Content Violation Room

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/mjolnir#333]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to shut down a room for reasons other than abuse.

**Describe the solution you'd like**
An optional flag on `!mjolnir shutdown room` maybe

**Describe alternatives you've considered**
Manually using the Admin API works, but is not very user friendly

**Additional context**
A customer asked me
>  Is there a way to shutdown a room that doesn't yank people into the Content Violation Room?
Some of my colleagues are wondering if they've been grounded.

**Comment by Twi1ightSparkle** [comment]
Backend, this is accomplished by simply calling the [shutdown room endpoint](https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#version-2-new-version) without `new_room_user_id` and `room_name` in the body

**Comment by turt2live** [comment]
Calling the API directly is encouraged in this case. The shutdown command is questionably part of the bot functions as a server admin function.
