### ISSUE TITLE
Aliasing commands

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/mjolnir#343]
**Is your feature request related to a problem? Please describe.**

When I am managing spam/flooder, I first `/ban @abus<TAB>` and then copy the MXID so I can go to the Mjolnir room and throw `!mjolnir redact <CTRL-V>`. This is a bit difficult, and would be more difficult if I happened to be on mobile.

**Describe the solution you'd like**

I would like to `alias` commands like I would in shell or IRC, `!mjolnir alias r="!mjolnir redact"`, so next time I can simply throw `!r <CTRL-V>` to have the spam go away faster with less effort.

Similarly should I find myself using some other commands a lot, I could ease using them by making up new aliases.

**Describe alternatives you've considered**

Proper moderation tools and the alias command could be implemented in clients, but I imagine doing that in Mjolnir to be significantly less effort and faster and not require a new MSC.

**Additional context**

I don't have access to Mjolnir config files and while I would be fine with aliases being configured there (as long as they would be exposed to me somehow), that would increase work for the Mjolnir host.

In IRC alias is a defacto standard. It's implemented in most of IRC clients, many bots support it in some form (I am mainly familiar with Supybot/Limnoria which have Alias/Aka plugins for this), IRC bouncers like ZNC have a module to configure aliases affecting all clients connecting to them and even some IRCd software has support for operators specifying serverside aliases for all users.

**Comment by rubo77** [comment]
Ok Android you can configure aliases in your keyboard settings. On a computer there are many tools for the same

**Comment by turt2live** [comment]
This is not a feature we're really able to support at the bot level. Client changes, and possibly protocol changes to support slash commands, would be best instead.
