### ISSUE TITLE
Mjolnir word is hard to remember

### ISSUE THREAD

**Issue by ajbura** [matrix-org/mjolnir#363]
**Is your feature request related to a problem? Please describe.**
I feel mjolnir is hard to remember when you are already dealing with stress of spammers flooding a room.

**Describe the solution you'd like**
Set an alias to it, could be `!mj` or something easy to come in mind. So that `!mj CMD` and `!mjolnir CMD` both works same.

**Comment by Philantrop** [comment]
cf. https://github.com/matrix-org/mjolnir/blob/main/config/default.yaml#L137 - it allows you to just do !CMD.

**Comment by mahdi1234** [comment]
You can also mention your mjolnir bot like `@username status`

**Comment by ajbura** [comment]
Thanks for the replies. I was thinking of having it a global alias by default which works along with !mjolnir or any other custom one via config irrespective of what someone has set in their config.

**Comment by turt2live** [comment]
As mentioned, the config and guide supports multiple ways to invoke the bot. The official documentation may also be linked to in your management room, making copy/paste an option.
