### ISSUE TITLE
Set room to invite only

### ISSUE THREAD

**Issue by tinywombat765** [matrix-org/mjolnir#367]
**Is your feature request related to a problem? Please describe.**
Our server has gotten a flood of bots joining a room. We'd like to be able to stop this.

**Describe the solution you'd like**
I'd like commands to be able to set a room as invite only then back to public again later.

**Describe alternatives you've considered**
Something automated would also be cool but hard tune.

**Additional context**
I'm willing to try to implement this, but would like feedback first. I also might need some help.

**Comment by Mikaela** [comment]
I would like to also have ability to set rooms knocking only or maybe even knock_restricted/restricted allowing joins by being a member of another protected room

**Comment by jae1911** [comment]
There is already something like that with the `JoinWaveShortCircuit` protection for the automated part:

![image](https://user-images.githubusercontent.com/76598503/188357500-76d865a9-7bc1-472d-9a17-2b85b8b397c4.png)

**Comment by turt2live** [comment]
Impersonating the bot or setting the room invite only from another admin account is supported.
