### ISSUE TITLE
Use `<details>` on large listings?

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/mjolnir#377]
When working on https://github.com/matrix-org/mjolnir/issues/294 (in https://github.com/matrix-org/mjolnir/pull/376), and live-testing it in the management room, I got a comment that the listings simply were *way* too big, and that hiding the text would be useful.

There is an HTML tag called [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) that would allow this, the Element Web client already supporting rendering of this;

![image](https://user-images.githubusercontent.com/22740616/193270644-3ffd201c-0dc4-4c9c-b9f9-5af6d1148a4f.png)

![image](https://user-images.githubusercontent.com/22740616/193270679-61096e77-5423-4272-83b3-ea2994e09607.png)

However, a quick look at the Element iOS client shows that it doesn't support it, and I don't know about Element Android.

This'd probably be nice in combination with the solution in #376, allowing users to hide massive walls of text but also quickly go to a specific subset of information in that large amount of text. (By just clicking the arrow next to the relevant header)

**Comment by turt2live** [comment]
This issue isn't actionable because it doesn't describe what it would affect other than "lots of text". The root issue here is https://github.com/matrix-org/mjolnir/issues/129 - we should keep conversation there.
