### ISSUE TITLE
Intercepting reports only works with Element clients

### ISSUE THREAD

**Issue by tux93** [matrix-org/mjolnir#387]
The Mjolnir reporting endpoint only works with clients that send reports to the `/_matrix/client/r0/rooms/` endpoint.

It does not work with other clients that send reports to `/_matrix/client/v3/rooms/`, in my case FluffyChat

For testing I adapted the location match in my nginx config to also forward requests to the v3 endpoint to Mjolnir but that leads to 504 errors for clients using the v3 endpoint while Element continues working  
```
location ~ ^/_matrix/client/(r0|v3)/rooms/([^/]*)/report/(.*)$ {
...
  set $room_id $2;
  set $event_id $3;
...
}
```

**Comment by turt2live** [comment]
Note that it's considered a bug that the Element clients call `r0` at all these days - Mjolnir should be resilient to this.

**Comment by ShadowJonathan** [comment]
Do you mean that mjolnir should not handle `r0`, or handle both?

**Comment by turt2live** [comment]
Probably handle both, but with the added pressure that the Element clients won't wait for Mjolnir to update when switching to not-`r0`

**Comment by Yoric** [comment]
Investigating.

**Comment by Yoric** [comment]
@tux93 That's weird, I have reproduced your nginx patch and it seems to pass tests for me.

**Comment by Yoric** [comment]
I have opened [a PR](https://github.com/matrix-org/mjolnir/pull/388) to update documentation and tests for this.

**Comment by tux93** [comment]
> @tux93 That's weird, I have reproduced your nginx.conf patch and it seems to pass tests for me.

I just tried it again as well and this time the report from Fluffy went through, maybe there was a hang up on the client side when initially testing
