### ISSUE TITLE
`config get` is broken

### ISSUE THREAD

**Issue by mjarr** [matrix-org/mjolnir#399]
Trying to query protection config values with `!mjolnir config get [protection]` fails with `No settings found` error.

I suspect it's because the function is trying to use `Object.keys` on `mjolnir.protections`, which is a `Map` according to the typings. `parts.length < 3` conditional also looks wrong to me as `parts` variable is created with `slice(3)` in `CommandHandler.ts`.

**Comment by Yoric** [comment]
@jesopo Could you take a look at this?
