### ISSUE TITLE
How to use mjolnir

### ISSUE THREAD

**Issue by mackiexx** [matrix-org/mjolnir#400]
Hello, i am confused where i should type the commands for mjolnir, i am typing it inside the room i invited it to but it is not working, please can someone tell me where to type these commands ? or basically how i can control mjolnir

**Comment by natrius** [comment]
The command should be typed in the management room like a normal message. When you start up mjolnir the bot gets invited to the room automatically and all the startup messages are also written into the chat.

**Comment by mackiexx** [comment]
> The command should be typed in the management room like a normal message. When you start up mjolnir the bot gets invited to the room automatically and all the startup messages are also written into the chat.

i invited the bot to the room before it started up, no commands was shown when it started. i am typing commands like "!mjolnir " and some prefixs i added in the conf file but it doesn't seem to recognize it
