### ISSUE TITLE
Error when starting mjolnir 

### ISSUE THREAD

**Issue by mackiexx** [matrix-org/mjolnir#405]
I am getting this errors when starting mjolnir 

`Tue, 01 Nov 2022 17:31:48 GMT [INFO] [index] Starting bot...
Tue, 01 Nov 2022 17:31:48 GMT [INFO] [index] Resolving protected rooms...
Tue, 01 Nov 2022 17:31:48 GMT [INFO] [index] Resolving management room...
Creating Web APIs
Tue, 01 Nov 2022 17:31:48 GMT [INFO] [index] Mjolnir is starting up. Use !mjolnir to query status.
Starting web server
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-18)] [Error: Error during MatrixClient request GET /_matrix/client/r0/user/%40modbot%domain.com/account_data/org.matrix.mjolnir.protected_rooms: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Account data not found"}]
Tue, 01 Nov 2022 17:31:49 GMT [WARN] [Mjolnir] { errcode: 'M_NOT_FOUND', error: 'Account data not found' }
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-22)] [Error: Error during MatrixClient request GET /_matrix/client/r0/user/%40modbot%domain.com/account_data/org.matrix.mjolnir.watched_lists: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Account data not found"}]
Tue, 01 Nov 2022 17:31:49 GMT [INFO] [Mjolnir@startup] Checking permissions...
Tue, 01 Nov 2022 17:31:49 GMT [INFO] [Mjolnir@startup] Syncing lists...
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-39)] [Error: Error during MatrixClient request GET /_matrix/client/r0/user/%40modbot%3Adomain.com/account_data/org.matrix.mjolnir.enabled_protections: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Account data not found"}]
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-40)] [Error: Error during MatrixClient request GET /_matrix/client/r0/rooms/!YhYxEvcuRlDMhIhRlv%3Adomain.com/state/org.matrix.mjolnir.setting/FirstMessageIsImageProtection: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Event not found."}]
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-42)] [Error: Error during MatrixClient request GET /_matrix/client/r0/user/%40modbot%3Adomaincom/account_data/org.matrix.mjolnir.enabled_protections: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Account data not found"}]
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-43)] [Error: Error during MatrixClient request GET /_matrix/client/r0/rooms/!YhYxEvcuRlDMhIhRlv%3Adomain.com/state/org.matrix.mjolnir.setting/BasicFloodingProtection: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Event not found."}]
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-44)] [Error: Error during MatrixClient request GET /_matrix/client/r0/user/%40modbot%3Adomain.com/account_data/org.matrix.mjolnir.enabled_protections: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Account data not found"}]
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-45)] [Error: Error during MatrixClient request GET /_matrix/client/r0/rooms/!YhYxEvcuRlDMhIhRlv%3Adomain.com/state/org.matrix.mjolnir.setting/WordList: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Event not found."}]
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-46)] [Error: Error during MatrixClient request GET /_matrix/client/r0/user/%40modbot%3Adomain.com/account_data/org.matrix.mjolnir.enabled_protections: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Account data not found"}]
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-47)] [Error: Error during MatrixClient request GET /_matrix/client/r0/rooms/!YhYxEvcuRlDMhIhRlv%3Adomain.com/state/org.matrix.mjolnir.setting/MessageIsVoiceProtection: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Event not found."}]
Tue, 01 Nov 2022 17:31:49 GMT [ERROR] [MatrixHttpClient (REQ-48)] [Error: Error during MatrixClient request GET /_matrix/client/r0/user/%40modbot%3Adomain.com/account_data/org.matrix.mjolnir.enabled_protections: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Account data not found"}]
Tue, 01 Nov 2022 17:31:50 GMT [ERROR] [MatrixHttpClient (REQ-49)] [Error: Error during MatrixClient request GET /_matrix/client/r0/rooms/!YhYxEvcuRlDMhIhRlv%3Adomain.com/state/org.matrix.mjolnir.setting/MessageIsMediaProtection: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Event not found."}]
Tue, 01 Nov 2022 17:31:50 GMT [ERROR] [MatrixHttpClient (REQ-50)] [Error: Error during MatrixClient request GET /_matrix/client/r0/user/%40modbot%3Adomain.com/account_data/org.matrix.mjolnir.enabled_protections: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Account data not found"}]
Tue, 01 Nov 2022 17:31:50 GMT [ERROR] [MatrixHttpClient (REQ-51)] [Error: Error during MatrixClient request GET /_matrix/client/r0/rooms/!YhYxEvcuRlDMhIhRlv%3Adomain.com/state/org.matrix.mjolnir.setting/TrustedReporters: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Event not found."}]
Tue, 01 Nov 2022 17:31:50 GMT [ERROR] [MatrixHttpClient (REQ-52)] [Error: Error during MatrixClient request GET /_matrix/client/r0/user/%40modbot%3Adomainc.om/account_data/org.matrix.mjolnir.enabled_protections: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Account data not found"}]
Tue, 01 Nov 2022 17:31:50 GMT [ERROR] [MatrixHttpClient (REQ-53)] [Error: Error during MatrixClient request GET /_matrix/client/r0/rooms/!YhYxEvcuRlDMhIhRlv%3Adomain.com/state/org.matrix.mjolnir.setting/DetectFederationLag: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Event not found."}]
Tue, 01 Nov 2022 17:31:50 GMT [ERROR] [MatrixHttpClient (REQ-54)] [Error: Error during MatrixClient request GET /_matrix/client/r0/user/%40modbot%3Adomain.com/account_data/org.matrix.mjolnir.enabled_protections: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Account data not found"}]
Tue, 01 Nov 2022 17:31:50 GMT [ERROR] [MatrixHttpClient (REQ-55)] [Error: Error during MatrixClient request GET /_matrix/client/r0/rooms/!YhYxEvcuRlDMhIhRlv%3Adomain.com/state/org.matrix.mjolnir.setting/JoinWaveShortCircuit: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Event not found."}]
Tue, 01 Nov 2022 17:31:50 GMT [INFO] [Mjolnir@startup] Startup complete. Now monitoring rooms.
`

**Comment by Gnuxie** [comment]
Hey, is your mjolnir working ok?

Unfortunately the logs describe a lot of irrelevant garbage because the matrix-bot-sdk reports every single http error as an error, and there isn't a way to turn it off. These aren't errors that you need to worry about, sorry for the false alarm.

**Comment by Yoric** [comment]
Sounds like the problem is with Pantalaimon. Perhaps https://matrix.to/#/#mjolnir:matrix.org would be a better place to chat with other users and see if someone can help?
