### ISSUE TITLE
Nonstop Abuse report

### ISSUE THREAD

**Issue by mackiexx** [matrix-org/mjolnir#406]
Mjolnir keeps sending same abuse report even after i've attended to it. it ought to stop as soon as an action is given.

**Comment by Yoric** [comment]
@mackiexx How is it configured? With the reverse proxy or with polling?

**Comment by mackiexx** [comment]
> @mackiexx How is it configured? With the reverse proxy or with polling?

I don't even know what is polling.

i followed the instruction on [READMD](https://github.com/matrix-org/mjolnir#readme) here and then i followed exactly what is on the installation page below . 

`git clone https://github.com/matrix-org/mjolnir.git
cd mjolnir

yarn install
yarn build

# Copy and edit the config. It *is* recommended to change the data path.
cp config/default.yaml config/development.yaml
nano config/development.yaml

node lib/index.js`

Then i copied this exact code below and added to my nginx file for reverse proxy. 

` location ~ ^/_matrix/client/(r0|v3)/rooms/([^/]*)/report/(.*)$ {
      # Abuse reports should be sent to Mjölnir.
      # The r0 endpoint is deprecated but still used by many clients.
      # As of this writing, the v3 endpoint is the up-to-date version.

      # Add CORS, otherwise a browser will refuse this request.
      add_header 'Access-Control-Allow-Origin' '*' always; # Note: '*' is for testing purposes. For your own server, you probably want to tighten this.
      add_header 'Access-Control-Allow-Credentials' 'true' always;
      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
      add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since' always;
      add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
      add_header 'Access-Control-Max-Age' 1728000; # cache preflight value for 20 days

      # Alias the regexps, to ensure that they're not rewritten.
      set $room_id $2;
      set $event_id $3;
      proxy_pass http://127.0.0.1:8082/api/1/report/$room_id/$event_id;
    }`

I also noticed along with this, Mjolnir doesn't work with Pantalaimon even though i have installed it and i don't know if it has to do with wrong configuration.

**Comment by mackiexx** [comment]
> @mackiexx How is it configured? With the reverse proxy or with polling?

To add, my mjolnir configuration looks like this

`web:
  # Whether to enable web APIs.
  enabled: true

  # The port to expose the webserver on. Defaults to 8080.
  port: 8082

  # The address to listen for requests on. Defaults to only the current
  # computer.
  address: localhost

  # Alternative setting to open to the entire web. Be careful,
  # as this will increase your security perimeter:
  #
  #  address: "0.0.0.0"

  # A web API designed to intercept Matrix API
  # POST /_matrix/client/r0/rooms/{roomId}/report/{eventId}
  # and display readable abuse reports in the moderation room.
  #
  # If you wish to take advantage of this feature, you will need
  # to configure a reverse proxy, see e.g. test/nginx.conf
  abuseReporting:
    # Whether to enable this feature.
    enabled: true

# Whether or not to actively poll synapse for abuse reports, to be used
# instead of intercepting client calls to synapse's abuse endpoint, when that
# isn't possible/practical.
pollReports: false

# Whether or not new reports, received either by webapi or polling,
# should be printed to our managementRoom.
displayReports: true`

**Comment by Yoric** [comment]
Mjölnir has two ways to fetch and display reports:

1. The reverse proxy (which you enabled with nginx, as above), which is the "best" way to display reports.
2. The polling (which you enabled with `pollReports`), which is designed as a fallback for people who cannot setup a reverse proxy for any reason, and displays fewer details about reports.

You seem to have both configured, so it will display reports twice. Does this match your experience?

**Comment by mackiexx** [comment]
> Mjölnir has two ways to fetch and display reports:
> 
> 1. The reverse proxy (which you enabled with nginx, as above), which is the "best" way to display reports.
> 2. The polling (which you enabled with `pollReports`), which is designed as a fallback for people who cannot setup a reverse proxy for any reason, and displays fewer details about reports.
> 
> You seem to have both configured, so it will display reports twice. Does this match your experience? Or does it display reports more than twice?

Yes, it displays more than twice even. Example: when you get a notification on your phone or say you have your phone ring out and you picked it up and silenced it, or even ignored the call, you took action with that and it is not suppose to ring again unless the person calls you back right? I tested by reporting an account, and the bot reported it to me so I took action and clicked the button “ignore the bad report”, the bot responded affirmative. Then within 2 seconds, same report is coming in again, over and over again.

**Comment by mackiexx** [comment]
> Mjölnir has two ways to fetch and display reports:
> 
> 1. The reverse proxy (which you enabled with nginx, as above), which is the "best" way to display reports.
> 2. The polling (which you enabled with `pollReports`), which is designed as a fallback for people who cannot setup a reverse proxy for any reason, and displays fewer details about reports.
> 
> You seem to have both configured, so it will display reports twice. Does this match your experience? Or does it display reports more than twice?

For some reason,  when i disabled poll reports, reporting a user doesn't show in the room again and i'm wondering if my reverse proxy is set up correctly

**Comment by Yoric** [comment]
So it feels like there is a problem with polling that somehow reports stuff more than once? I'll investigate that.

**Comment by Yoric** [comment]
Oh... we seem to be forgetting to store `from`! Definitely a bug!

**Comment by mackiexx** [comment]
> ~Oh... we seem to be forgetting to store `from`! Definitely a bug!~
> 
> My bad, we do store it.

Did you manage to find anything?

**Comment by ThoreKr** [comment]
IIm observing the same behaviour with admin api polling.
Every minute it will post all reports over and over again.

**Comment by Pecadis** [comment]
Hi,
just wanted to join the conversation as i am facing the same issue even after a year.
@Yoric did you manage to find something in this regard?

**Comment by paddatrapper** [comment]
Chiming in on this - we are seeing the same thing with our Mjolnir instance. It keeps displaying reports again and again, even if we deal with them (via reactions and confirmation reactions).

**Comment by turt2live** [comment]
I'm assuming this is fixed or a possible misconfiguration. A new issue with fresh logs would be helpful if folks are seeing this still.
