### ISSUE TITLE
Pills and mjolnir commandlines don't mix

### ISSUE THREAD

**Issue by ara4n** [matrix-org/mjolnir#43]
It's not obvious that a pill expands to an mxid, so if you try to suffix it with a domain, badness

**Comment by turt2live** [comment]
not sure there's much we can do about this from this side: the bot already handles pills in commands (for most commands/cases), but suffixing on a second server domain is largely unexpected by any client implementation.

**Comment by turt2live** [comment]
This feels like a client problem and less so one that Mjolnir can solve (as it'd affect all kinds of bots and other clients)
