### ISSUE TITLE
Mjolnir is persisting aliases to `org.matrix.mjolnir.watched_lists`.

### ISSUE THREAD

**Issue by Gnuxie** [matrix-org/mjolnir#435]
This is causing problems if a server temporarily goes offline or the alias has been changed. When mjolnir starts it will exit if an alias of a watched list cannot be resolved. But it shouldn't be storing aliases in the first place. 

We've had 2-3 complaints about it in #mjolnir:matrix.org over the past weeks, probably related to https://github.com/matrix-org/mjolnir/pull/385

https://matrix.to/#/!WpbOWAblxueZXAAnjj:matrix.org/$01Ybf7KmxL2elK7hV8gXkopPLscCTylaibjpiftNTyM?via=matrix.org&via=envs.net&via=element.io

**Comment by mahdi1234** [comment]
Might want to link with other one created earlier :) - #404

**Comment by Gnuxie** [comment]
Can confirm that this is a pretty bad problem with the `﻿#community-moderation-effort-bl:neko.dev` alias.

**Comment by turt2live** [comment]
Presuming fixed by https://github.com/matrix-org/mjolnir/pull/518

If not, please open a new issue with fresh logs.
