### ISSUE TITLE
Allow redacting a user at the same time they get banned

### ISSUE THREAD

**Issue by ghost** [matrix-org/mjolnir#438]
I propose changing the `!mjolnir ban` command syntax to something like this:

`!mjolnir ban banlist @evilusertoredact:example.com redact banreason`

if the `redact` word is not present in between the Matrix ID and the reason, mjolnir shouldn't redact the user, if it is present, it should redact every message sent by the user.

Our current syntax is

`!mjolnir ban banlist @eviluser:example.com banreason`

Should we allow specifying a redact reason too? like this:

`!mjolnir ban banlist @evilusertoredact:example.com redact redactreason banreason`

Or we could also use the same reason for banning and redacting.

**Comment by Gnuxie** [comment]
`automaticallyRedactForReasons` in the [config](https://github.com/matrix-org/mjolnir/blob/main/config/default.yaml#L82-L95) exists for this purpose.

**Comment by JokerGermany** [comment]
Would like a command, too.
When you use a different Reason for every ban, you can't use the config...

**Comment by turt2live** [comment]
https://github.com/matrix-org/mjolnir/issues/438#issuecomment-1328772865
