### ISSUE TITLE
Crash on rate limit exceeded

### ISSUE THREAD

**Issue by FedericoCeratto** [matrix-org/mjolnir#456]
Mjolnir 1.6.1 crashed out when hitting a rate limit:
```7: 429 Too Many Requests -- {"errcode":"M_LIMIT_EXCEEDED","error":"Too Many Requests","retry_after_ms":2331}]
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
```

There are cases when giving admin rights to Mjolnir is not possible or unwanted. Is in possible to have a form of throttling?
Thanks

Related to #27

**Comment by Yoric** [comment]
Do you have the full error message?

Currently, Mjölnir retries throttled messages but does not retry timeouts. Is this one of these cases?

**Comment by turt2live** [comment]
Closing due to lack of reply.
