### ISSUE TITLE
Constant stream of 404 errors around state/m.room.canonical_alias

### ISSUE THREAD

**Issue by FedericoCeratto** [matrix-org/mjolnir#457]
Mjolnir is frequently logging the following error. 
Unlike other bug reports, it's not crashing out and appears to be working.

```
Mon, 12 Dec 2022 12:24:34 GMT [ERROR] [MatrixHttpClient] (REQ-8950) [Error: Error during MatrixClient request GET /_matrix/client/v3/rooms/REDACTED/state/m.room.canonical_alias/: 404 Not Found -- {"errcode":"M_NOT_FOUND","error":"Event not found."}]
```
(room name redacted by me)
Thanks!

**Comment by Yoric** [comment]
Yes, that's an unfortunate artifact of using matrix-bot-sdk. I have attempted to open a PR to help alleviate this, but it never got traction. Not sure how it can be resolved.

**Comment by turt2live** [comment]
This is an upstream issue.
