### ISSUE TITLE
Suggest deactivating user whenever someone is banned for spam

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/mjolnir#459]
When we `!mjolnir ban` someone, the bans only apply to Mjolnir protected rooms. This means that the spammer can still go around and attack other unprotected rooms and rooms on other servers.

After banning, it would be nice if Mjolnir suggested `!mjolnir deactivate` so we never forget. Deactivating the account stops the spammer from using the server altogether. This could be a 1-minute follow-up question with some quick actions to proceed/ignore or we could do the action automatically as a sane default.

**Comment by MadLittleMods** [comment]
Another probably better alternative to deactivating an account which is destructive action is to use [shadow bans](https://github.com/matrix-org/mjolnir/issues/266) and [MSC3939 for account locking](https://github.com/matrix-org/matrix-spec-proposals/pull/3939).

Although deactivation is at least a step forward iteration in any case.

**Comment by turt2live** [comment]
This feels highly risky considering the variety of accounts which get banned for spam. I'd prefer if we didn't recommend anything, but made documentation available for example policy.
