### ISSUE TITLE
Puppet and redact all messages sent by the user

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/mjolnir#460]
Currently `!mjolnir redact` only works on the backlog of messages in protected rooms. But often spam is spread beyond to unprotected rooms and beyond the server where Mjolnir lives.

If we see someone spamming on the same server where Mjolnir lives, we should clean-up all of messages they have sent. We can puppet the bad user to redact their messages in all the places they sent them even if the Mjolnir user isn't in the room.

**Comment by MadLittleMods** [comment]
> by puppeting the user, do you mean taking over their account using server admin permissions and forcing them to redact their messages?

Correct 👍

The point is that even if the Mjolnir user isn't in the room or has power levels, the spam can be redacted across the board from the bad-actor.

**Comment by H-Shay** [comment]
Should be fixed by https://github.com/matrix-org/mjolnir/pull/538.
