### ISSUE TITLE
Why does `unban` have `apply`, and why is it default-false?

### ISSUE THREAD

**Issue by grahamc** [matrix-org/mjolnir#476]
I find I almost always unban first without apply. Then, when I realize my mistake I have to re-ban them then unban them again with `apply` for it to actually work.

... why is unban built the way that it is?

**Comment by turt2live** [comment]
Originally Mjolnir was intended to be purely a way to manage banlists, then during development it gained the ability to actually do the bans itself. The unban command was thought to be more dangerous, so a flag was added to actually apply the unban.

The other reason is internally to the code is no logical separation between an unban issued by a list you control versus a list you don't control: for safety, unbans are not automatically applied and instead someone needs to manually apply them with the unban command.
