### ISSUE TITLE
Mjolnir unban also removes allow rules

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/mjolnir#482]
I am following a Mjolnir list that includes `matrix.org` ban due to matrix-public-archive and I encountered this trying to get rid of it.

I executed something like `!mjolnir unban shortcode server matrix.org apply` and as a result it removed two rules:

```json
{
  "entity": "*",
  "reason": "Default allow rule",
  "recommendation": "org.matrix.mjolnir.allow"
}
```

```json
{
  "entity": "matrix.org",
  "reason": "Attempting to override matrix.org ban from list",
  "recommendation": "org.matrix.mjolnir.allow"
}
```

This temporarily resulted in ACL rule without the `*`.

***SUGGESTION: Never remove `org.matrix.mjolnir.allow` rules with the `unban` command.***

**Comment by turt2live** [comment]
This does not appear to be a feature of Mjolnir. Please include more information about where the allow rule is coming from, in code if possible, and reopen as needed.
