### ISSUE TITLE
(M_LIMIT_EXCEEDED) in home server

### ISSUE THREAD

**Issue by leonardorortizm** [matrix-org/mjolnir#485]
Hi, people, I'm having an issue with my homeserver getting this error when i'm trying to login via element app: (An error occurred connecting to your home server, please try again later.(M_LIMIT_EXCEEDED) how can i to solve this problem.

This is my homeserver.yaml

# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "matrix.superredes.co"
pid_file: /home/ubuntu/synapse/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false
database:
  name: sqlite3
  args:
    database: /home/ubuntu/synapse/homeserver.db
log_config: "/home/ubuntu/synapse/matrix.superredes.co.log.config"
media_store_path: /home/ubuntu/synapse/media_store
registration_shared_secret: "erLW&R-oSZbNT=ChQoUN:C2Ony3;d*mH,IG5JgAdKG_:GHqbKr"
report_stats: false
macaroon_secret_key: "bRUkm7uf68xMy_DczLnH:8BKl-UuxLNY_C8:cdN8XzEEZc:#aX"
form_secret: ".10qV286Sj9muotB0ThgUA6B*DTXVtLttB6vP_W*3KGF4S;GNE"
signing_key_path: "/home/ubuntu/synapse/matrix.superredes.co.signing.key"
trusted_key_servers:
  - server_name: "matrix.superredes.co"
enable_registration: true
#enable_registration_without_verification: true
enable_registration_captcha: true
recaptcha_public_key: "6Ld5l3IUAAAAACSwuBgr7ADfJQe1l5nmjq7F-jeK"
recaptcha_private_key: "6Ld5l3IUAAAAAOYQ_at3bRXVsAjS-5yepkT3L5sD"
max_upload_size: 500M
auto_join_rooms:
  - "#chat_general_sr:matrix.superredes.co"
modules:
 - module: "matrix_e2ee_filter.EncryptedRoomFilter"
   config:
     deny_encryption_for_users_of: ['matrix.superredes.co']
     deny_encryption_for_rooms_of: ['matrix.superredes.co']

#acept_invites_only_for_direct_messages: true
# vim:ft=yaml

**Comment by turt2live** [comment]
This doesn't appear related to Mjolnir. Please consult the support room for your software.
