### ISSUE TITLE
Print 'event reports' to control room. (Feature Request)

### ISSUE THREAD

**Issue by PC-Admin** [matrix-org/mjolnir#488]
So event reports are very useful for moderators and there seems to be no easy way of piping the event reports seen here into your mjolnir control room without creating another bot for this purpose: https://matrix-org.github.io/synapse/latest/admin_api/event_reports.html

It would be cool if mjolnir had an option to just print any new event reports to the control room. That way moderators could get a live feed of these reports and actually respond to them.

On my server (and I suspect many others) these reports are only viewed once in a blue moon and can only be viewed by server administrators, which isn't ideal.

**Comment by PC-Admin** [comment]
I saw this command and thought perhaps it was what I needed `!mjolnir rooms setup !wAeZacOKvaHPcSqxAW:perthchat.org reporting` but that doesn't seem to do this... (I'm not actually sure what that does tbh.)

**Comment by H-Shay** [comment]
I think the bot has this capability? Does https://github.com/matrix-org/mjolnir?tab=readme-ov-file#enabling-readable-abuse-reports cover your usecase?

**Comment by turt2live** [comment]
Presuming addressed - please reopen or open a new issue if there's work outstanding here.
