### ISSUE TITLE
Wildcard kick - don't try and kick users who are not in a room

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/mjolnir#489]
There are now thousands of these in the moderation room
![Screenshot 2023-08-16 at 11 39 52 AM](https://github.com/matrix-org/mjolnir/assets/19155609/0d7e400c-c51b-476f-9f4c-ee38c459af57)

**Comment by turt2live** [comment]
This is indicative of a server issue and should be investigated there. In general though, Mjolnir over-performing is considered a feature.
