### ISSUE TITLE
Unable to start mjolnir in k8s, TLS error

### ISSUE THREAD

**Issue by cristi-vlad** [matrix-org/mjolnir#490]
Hello,

App is not starting in k8s, probably seeking for CA certificate of matrix server BUT there is no way to set it :

Thu, 31 Aug 2023 08:35:56 GMT [ERROR] [MatrixHttpClient] (REQ-1) Error: unable to verify the first certificate
Thu, Aug 31 2023 10:35:56 am at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
Thu, Aug 31 2023 10:35:56 am at TLSSocket.emit (node:events:513:28)
Thu, Aug 31 2023 10:35:56 am at TLSSocket.emit (node:domain:489:12)
Thu, Aug 31 2023 10:35:56 am at TLSSocket._finishInit (node:_tls_wrap:953:8)
Thu, Aug 31 2023 10:35:56 am at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
Thu, Aug 31 2023 10:35:56 am code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
Thu, Aug 31 2023 10:35:56 am}
Thu, Aug 31 2023 10:35:56 amFailed to setup mjolnir from the config /data/storage: Error: unable to verify the first certificate
Thu, Aug 31 2023 10:35:56 amnode:internal/process/promises:279
Thu, Aug 31 2023 10:35:56 am triggerUncaughtException(err, true /* fromPromise */);
Thu, Aug 31 2023 10:35:56 am ^
Thu, Aug 31 2023 10:35:56 am
**Thu, Aug 31 2023 10:35:56 amError: unable to verify the first certificate
Thu, Aug 31 2023 10:35:56 am at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)**
Thu, Aug 31 2023 10:35:56 am at TLSSocket.emit (node:events:513:28)
Thu, Aug 31 2023 10:35:56 am at TLSSocket.emit (node:domain:489:12)
Thu, Aug 31 2023 10:35:56 am at TLSSocket._finishInit (node:_tls_wrap:953:8)
Thu, Aug 31 2023 10:35:56 am at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12) {
Thu, Aug 31 2023 10:35:56 am code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
Thu, Aug 31 2023 10:35:56 am}

**Comment by turt2live** [comment]
This is not something Mjolnir can resolve. Your server must present a valid certificate.
