### ISSUE TITLE
Support removing someone from the internal auto-redact list (after a protection activates)

### ISSUE THREAD

**Issue by turt2live** [matrix-org/mjolnir#530]
Currently the steps an admin must take are:
1. Manually unban the user from the affected room
2. Restart Mjolnir so it doesn't auto-redact them anymore.

Ideally, this would be condensed down to:
1. `!mjolnir unban @user:example.org true`

and that also removes them from the internal auto-redact list.

**Comment by H-Shay** [comment]
Does https://github.com/matrix-org/mjolnir/blob/cf6f61b09aeb9d463a2f8b9a85680a495dcbf6ba/src/commands/UnbanBanCommand.ts#L126-LI71 just not work? Looking at the code it appears to unban someone from the protected rooms and remove them from `unlistedUserRedactionHandler` - am I missing something here?

**Comment by turt2live** [comment]
It hasn't worked for us in production, but that may be because we were outdated at the time. Testing may be required.

I can believe (without looking at the code) that if it fails to remove from the banlist then it'll fail to remove from the autoredact list too.
