### ISSUE TITLE
Disable users on homeserver

### ISSUE THREAD

**Issue by ThoreKr** [matrix-org/mjolnir#65]
Server admins can deactivate users either through element or the admin API.

I'd like to outsource this capability to a bot.

Would a PR for such a feature be welcome?

**Comment by turt2live** [comment]
`!mjolnir deactivate <user>`

**Comment by ThoreKr** [comment]
Oh, thanks for the quick reply. I totally missed that. Should this be added to the documentation?

**Comment by turt2live** [comment]
The command structure needs work before documentation should be written on it, imo
