### ISSUE TITLE
Cannot ban user who was banned

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/mjolnir#69]
**Describe the bug**
I banned a user with `!mjolnir ban @someone:homeserver.tld`, then issued the command `!mjolnir redact @someone:homeserver.tld`

The ban command message have the checkmark ✅

The redact command message have the `In Progress` reaction, after almost 2 hours

This is what mjolnir returned:
```
moderator
Banning @someone:homeserver.tld in @someRoom:anotherHomeserver.tld for: <no reason supplied>
Banning @someone:homeserver.tld in @someRoom:anotherHomeserver.tld for: <no reason supplied>

twilight

    !mjolnir redact @someone:homeserver.tld

There was an error processing your command - see console/log for details
Errors updating member bans:
1 errors updating protected rooms!

    @someRoom:anotherHomeserver.tld - Cannot ban user who was banned

moderator
Done updating rooms - no errors
```

But, the user was successfully banned from the room 
`moderator banned someone. Reason: <no reason supplied>`

Unfortunately I forgot to save console log, and when I dumped it now 2 hours later and searched for someone, nothing is found.

**To Reproduce**
1. not sure, beyond doing what I described above

**Expected behavior**
Not throw that error, since the user was actually banned. Or throw a more specific error if the problem is something else. Like ordering of commands, latency of servers etc.

**Screenshots**
Available on request. Cannot post publicly 

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6 (19G73)
 - Browser: Firefox
 - Version: 80.0.1 (64-bit)

**Comment by turt2live** [comment]
without logs it's going to be impossible to figure out why it decided to try and ban the user twice. The error is correct given what the bot did.

The redaction issue is something that will also require logs, and is a different problem.

**Comment by Twi1ightSparkle** [comment]
I can send you the console dump I made, maybe you can see something I can't.

**Comment by turt2live** [comment]
This is caused by a timing issue where someone else changed their membership event at the same time Mjolnir was processing the ban. We might want to be more careful about it, but as a low priority item.

**Comment by heftig** [comment]
I've also seen this multiple times, and I don't think it's because Mjolnir races with the user.

```
heftig: !ban @bad:user spam
✅1
mjolnir: Banning @bad:user in Room Name for: spam
mjolnir: Banning @bad:user in Room Name for: spam
mjolnir: 1 errors updating protected rooms!

    Room Name - Cannot ban user who was banned

mjolnir: Done updating rooms - no errors
```

Could this be a race between the command and Mjolnir reacting to its own modification of the banlist?

**Comment by turt2live** [comment]
I think this is a race condition that's okay to have. We can't really fix this sort of thing easily, and the fact that it's trying to ban someone repeatedly is a Good Thing.
