### ISSUE TITLE
When the bot endlessly retries an action, it will also spam the inappropriate mxid into the moderation room

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/mjolnir#72]
I guess you should say the moderation team should be fine with inappropriate user_ids, but it wouldn't hurt to censor the names with some kind of simple word filter for subsequent log lines. Even if not for matrix.org usage, it would be good for other users.

**Comment by turt2live** [comment]
This is intentional and by design. It's not retrying, it is actually taking the action again following a trigger.

The errors are suppressed because other people complained about those.

**Comment by Half-Shot** [comment]
>This is intentional and by design. It's not retrying, it is actually taking the action again following a trigger.

I think this might be beside the point. It's more that the output from the bot ends up being more offensive than the user's actual actions :/

**Comment by turt2live** [comment]
Have opened https://github.com/matrix-org/mjolnir/issues/73 - I thought we had an issue for it already, but it must have only been discussed internally
