### ISSUE TITLE
Replace shutdown_room and purge_room APIs with delete_room

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/mjolnir#76]
Synapse is dropping the `shutdown_room` and `purge_room` APIs in favour of the `delete_room` API which handles both operations and more. Context: https://github.com/matrix-org/synapse/pull/8829

Please update your code to use this new endpoint instead :slight_smile:

**Comment by richvdh** [comment]
Hi mjolnir maintainers (@turt2live?), quick reminder that we're planning to drop support for these APIs in Synapse in a couple of weeks.

**Comment by turt2live** [comment]
@richvdh There's theoretically a team which manages Mjolnir these days. I'll bring it up with them.

**Comment by richvdh** [comment]
Hi folks, just a reminder that we'll be disabling these APIs on develop as soon as we've cut Synapse 1.41rc1, which is due to happen today - so it's likely that matrix.org will drop the old APIs within the next couple of days.
