### ISSUE TITLE
Action "unflag as spam" on messages when removing room or user from ban list

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/mjolnir#79]
**Is your feature request related to a problem? Please describe.**
Mjolnir have "block_messages: true" mode, that flag messages sent by servers/users in the ban lists as spam (Currently this means that spammy messages will appear as empty to users).

But sometimes rooms and users are added to ban list by mistakes, so we need the way to revert this action and "unflag as spam" those messages, to return to users the ability to see these messages.

**Describe the solution you'd like**
Implement  "unflag as spam" action on messages when removing room from ban list.

**Comment by turt2live** [comment]
This is the unban command.
