### ISSUE TITLE
Notify admins when bot is @-mentioned

### ISSUE THREAD

**Issue by heftig** [matrix-org/mjolnir#89]
**Is your feature request related to a problem? Please describe.**
Users requesting moderation from the bot aren't heard. 

**Describe the solution you'd like**
The bot should send a message containing `@room` to its admin room when it is mentioned in another room. This reaction should be rate-limited.

**Describe alternatives you've considered**
Users can still contact individual moderators but this defeats the anonymity of the bot's actions.

**Comment by turt2live** [comment]
`@room` is maybe a bit strong, but batching or general noise from the bot could be helpful to bump the activity of the management room. A config option would be valuable.

**Comment by Justinzobel** [comment]
I tried to use this, but it didn't seem to work.

I used `!Mjolnir enable forwardMentionsToManagementRoom` and Mjolnir replied with ✅ but when I reply to a comment and mention the bot tag e.g. `@mybot:myserver.net` it doesn't show up with anything in our moderation room.

**Comment by turt2live** [comment]
I'd suggest opening a new issue with relevant logs so we can investigate.

**Comment by Justinzobel** [comment]
> I'd suggest opening a new issue with relevant logs so we can investigate.

I'll ask my homeserver admin to get the logs, thanks for the quick reply!
